import type { Metadata } from "next";
import "./globals.css";
import { geistSans, geistMono } from "@/ui/fonts";
import Sidebar from "@/components/sidebar";
import News from "@/components/news";
import { defaultUrl } from "@/utils/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  metadataBase: new URL(defaultUrl),
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased text-sm`}>
        <div className="flex justify-between max-w-6xl mx-auto">
          <div className="">
            <Sidebar />
          </div>
          <main>{children}</main>
          <div className="">
            <News />
          </div>
        </div>
      </body>
    </html>
  );
}
