import type { Metadata } from "next";
import "./globals.css";
import { geistSans, geistMono } from "@/ui/fonts";
import Sidebar from "@/components/sidebar";
import News from "@/components/news";
import { defaultUrl } from "@/utils/utils";
import { AuthProvider } from "@/utils/context/AuthContext";
import { getCurrentUser } from "@/utils/supabase/actions";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  metadataBase: new URL(defaultUrl),
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser(); // Fetch user from Supabase or cookies (server-side).

  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased text-sm`}>
        <AuthProvider initialUser={user}>
          <div className="flex justify-between max-w-6xl mx-auto">
            <div className="">
              <Sidebar />
            </div>
            <main className="w-full">{children}</main>
            <div className="">
              <News />
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
